CREATE TABLE IF NOT EXISTS public.vip_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    order_id TEXT NOT NULL UNIQUE,
    payment_url TEXT NOT NULL,
    inv_id TEXT NOT NULL UNIQUE,
    amount INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'failed_or_expired', 'unknown', 'poll_error', 'timeout')),
    buyer_name TEXT NOT NULL,
    buyer_email TEXT NOT NULL,
    qris_amount TEXT NOT NULL DEFAULT '',
    qris_expires TEXT NOT NULL DEFAULT '',
    invite_link TEXT,
    invite_expires_at TIMESTAMPTZ,
    error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vip_payments_user_status
ON public.vip_payments (user_id, status, id DESC);

CREATE INDEX IF NOT EXISTS idx_vip_payments_status_id
ON public.vip_payments (status, id ASC);

ALTER TABLE public.vip_payments ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_payments FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_payments TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_payments_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.vip_bot_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_bot_settings ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_bot_settings FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_bot_settings TO service_role;
