CREATE TABLE IF NOT EXISTS public.vip_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    package_code TEXT NOT NULL DEFAULT '',
    package_name TEXT NOT NULL DEFAULT '',
    package_amount INTEGER NOT NULL DEFAULT 0,
    vip_chat_id BIGINT,
    invite_expire_hours INTEGER NOT NULL DEFAULT 0,
    public_invoice_id TEXT NOT NULL,
    order_id TEXT NOT NULL UNIQUE,
    payment_url TEXT NOT NULL,
    inv_id TEXT NOT NULL UNIQUE,
    amount INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'pending',
            'processing_paid',
            'invite_error',
            'processing_delivery',
            'delivery_error',
            'delivery_blocked',
            'paid',
            'failed_or_expired',
            'unknown',
            'poll_error',
            'timeout'
        )
    ),
    buyer_name TEXT NOT NULL,
    buyer_email TEXT NOT NULL,
    qris_amount TEXT NOT NULL DEFAULT '',
    qris_expires TEXT NOT NULL DEFAULT '',
    qris_chat_id BIGINT,
    qris_message_id BIGINT,
    next_check_at TIMESTAMPTZ,
    poll_attempts INTEGER NOT NULL DEFAULT 0,
    last_polled_at TIMESTAMPTZ,
    invite_link TEXT,
    invite_expires_at TIMESTAMPTZ,
    error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vip_payments_user_status
ON public.vip_payments (user_id, status, id DESC);

CREATE INDEX IF NOT EXISTS idx_vip_payments_status_id
ON public.vip_payments (status, id ASC);

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS public_invoice_id TEXT;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS package_code TEXT NOT NULL DEFAULT '';

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS package_name TEXT NOT NULL DEFAULT '';

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS package_amount INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS vip_chat_id BIGINT;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS invite_expire_hours INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS qris_chat_id BIGINT;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS qris_message_id BIGINT;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS next_check_at TIMESTAMPTZ;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS poll_attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS last_polled_at TIMESTAMPTZ;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS referral_id BIGINT;

ALTER TABLE public.vip_payments
ADD COLUMN IF NOT EXISTS referrer_user_id BIGINT;

UPDATE public.vip_payments
SET next_check_at = now()
WHERE status IN ('pending', 'invite_error', 'delivery_error')
  AND next_check_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_vip_payments_next_check
ON public.vip_payments (next_check_at ASC, id ASC)
WHERE status IN ('pending', 'invite_error', 'delivery_error');

CREATE INDEX IF NOT EXISTS idx_vip_payments_package_code
ON public.vip_payments (package_code);

ALTER TABLE public.vip_payments
DROP CONSTRAINT IF EXISTS vip_payments_status_check;

ALTER TABLE public.vip_payments
ADD CONSTRAINT vip_payments_status_check
CHECK (
    status IN (
        'pending',
        'processing_paid',
        'invite_error',
        'processing_delivery',
        'delivery_error',
        'delivery_blocked',
        'paid',
        'failed_or_expired',
        'unknown',
        'poll_error',
        'timeout'
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_vip_payments_public_invoice_id
ON public.vip_payments (public_invoice_id);

WITH ranked_active_payments AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY user_id
            ORDER BY created_at DESC, id DESC
        ) AS active_rank
    FROM public.vip_payments
    WHERE status IN (
        'pending',
        'processing_paid',
        'invite_error',
        'processing_delivery',
        'delivery_error'
    )
)
UPDATE public.vip_payments AS payment
SET
    status = 'timeout',
    error = 'Closed duplicate active payment before one-active-per-user index',
    updated_at = now()
FROM ranked_active_payments AS ranked
WHERE payment.id = ranked.id
  AND ranked.active_rank > 1;

CREATE UNIQUE INDEX IF NOT EXISTS idx_vip_payments_one_active_per_user
ON public.vip_payments (user_id)
WHERE status IN (
    'pending',
    'processing_paid',
    'invite_error',
    'processing_delivery',
    'delivery_error'
);

ALTER TABLE public.vip_payments ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_payments FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_payments TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_payments_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.vip_bot_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_bot_settings ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_bot_settings FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_bot_settings TO service_role;

CREATE TABLE IF NOT EXISTS public.vip_packages (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    vip_chat_id BIGINT NOT NULL,
    amount INTEGER NOT NULL CHECK (amount >= 1000 AND amount <= 10000000),
    invite_expire_hours INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vip_packages
ADD COLUMN IF NOT EXISTS invite_expire_hours INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.vip_packages
ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE public.vip_packages
ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 100;

ALTER TABLE public.vip_packages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_packages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_packages TO service_role;

CREATE TABLE IF NOT EXISTS public.vip_users (
    user_id BIGINT PRIMARY KEY,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    referral_code TEXT NOT NULL UNIQUE,
    invited_by_user_id BIGINT,
    balance INTEGER NOT NULL DEFAULT 0,
    pending_referrals INTEGER NOT NULL DEFAULT 0,
    successful_referrals INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vip_users_referral_code
ON public.vip_users (referral_code);

CREATE INDEX IF NOT EXISTS idx_vip_users_invited_by
ON public.vip_users (invited_by_user_id);

ALTER TABLE public.vip_users ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_users FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_users TO service_role;

CREATE OR REPLACE FUNCTION public.vip_increment_pending_referral(p_user_id BIGINT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE public.vip_users
    SET pending_referrals = pending_referrals + 1,
        updated_at = now()
    WHERE user_id = p_user_id;
$$;

CREATE OR REPLACE FUNCTION public.vip_credit_referral_commission(p_user_id BIGINT, p_amount INTEGER)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE public.vip_users
    SET balance = balance + GREATEST(p_amount, 0),
        pending_referrals = GREATEST(pending_referrals - 1, 0),
        successful_referrals = successful_referrals + 1,
        updated_at = now()
    WHERE user_id = p_user_id;
$$;

CREATE OR REPLACE FUNCTION public.vip_credit_balance(p_user_id BIGINT, p_amount INTEGER)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE public.vip_users
    SET balance = balance + GREATEST(p_amount, 0),
        updated_at = now()
    WHERE user_id = p_user_id;
$$;

REVOKE ALL ON FUNCTION public.vip_increment_pending_referral(BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_credit_referral_commission(BIGINT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_credit_balance(BIGINT, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.vip_increment_pending_referral(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_credit_referral_commission(BIGINT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_credit_balance(BIGINT, INTEGER) TO service_role;

CREATE TABLE IF NOT EXISTS public.vip_referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_user_id BIGINT NOT NULL,
    referrer_code TEXT NOT NULL,
    invited_user_id BIGINT NOT NULL UNIQUE,
    invited_username TEXT NOT NULL DEFAULT '',
    invited_full_name TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    payment_inv_id TEXT,
    package_code TEXT NOT NULL DEFAULT '',
    package_amount INTEGER NOT NULL DEFAULT 0,
    commission_amount INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vip_referrals_referrer_status
ON public.vip_referrals (referrer_user_id, status, id DESC);

CREATE INDEX IF NOT EXISTS idx_vip_referrals_referrer_code
ON public.vip_referrals (referrer_code);

ALTER TABLE public.vip_referrals ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_referrals FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_referrals TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_referrals_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.vip_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    amount INTEGER NOT NULL CHECK (amount > 0),
    phone TEXT NOT NULL,
    wallet_name TEXT NOT NULL,
    account_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'rejected')),
    admin_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vip_withdrawals_user_status
ON public.vip_withdrawals (user_id, status, id DESC);

ALTER TABLE public.vip_withdrawals ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vip_withdrawals FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.vip_withdrawals TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vip_withdrawals_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.vip_create_withdrawal(
    p_user_id BIGINT,
    p_username TEXT,
    p_full_name TEXT,
    p_amount INTEGER,
    p_phone TEXT,
    p_wallet_name TEXT,
    p_account_name TEXT
)
RETURNS SETOF public.vip_withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    created public.vip_withdrawals;
BEGIN
    IF p_amount <= 0 THEN
        RETURN;
    END IF;

    UPDATE public.vip_users
    SET balance = balance - p_amount,
        phone = p_phone,
        updated_at = now()
    WHERE user_id = p_user_id
      AND balance >= p_amount;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    INSERT INTO public.vip_withdrawals (
        user_id,
        username,
        full_name,
        amount,
        phone,
        wallet_name,
        account_name,
        status,
        created_at,
        updated_at
    ) VALUES (
        p_user_id,
        p_username,
        p_full_name,
        p_amount,
        p_phone,
        p_wallet_name,
        p_account_name,
        'pending',
        now(),
        now()
    ) RETURNING * INTO created;

    RETURN NEXT created;
END;
$$;

REVOKE ALL ON FUNCTION public.vip_create_withdrawal(BIGINT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.vip_create_withdrawal(BIGINT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT) TO service_role;
